### ISSUE TITLE
WebSocketError: I/O failure

### ISSUE THREAD

**Issue by rambontanga** [timvisee/ffsend#88] opened 2019-08-01 21:30 UTC
I am getting this error while trying to upload a file. 
PS: I was using the -f flag

Encrypt & Upload 1.23 GB / 1.32 GB [=======================================================================================================================>--------] 93.45 % 13.38 MB/s 7s error: failed to upload the specified file
caused by: failed to upload the file
caused by: failed to stream file for upload over websocket
caused by: WebSocketError: I/O failure

**Comment by timvisee** [comment] 2019-08-01 21:54
Does this happen repeatedly? Also, why is the `-f` used?

**Comment by rambontanga** [comment] 2019-08-01 21:56
Yes.
I tried that since the file is over 1 Gb and was not quite sure if it was possible to log with my firefox send account.

**Comment by timvisee** [comment] 2019-08-04 21:38
> ...the file is over 1 Gb and was not quite sure if it was possible to log with my firefox send account.

This issue is probably caused because you're not authenticated (in `ffsend`) then, making the limit just 1GB.

Sadly it currently is not possible to authenticate with your Firefox account within `ffsend`. I'd like to implement support for this, but it's currently blocked by Mozilla. They don't support 3rd party applications using their authentication service at this time.

See (and follow) this issue on GitLab for any progress updates on this: https://gitlab.com/timvisee/ffsend/issues/58

Assuming this issue was caused by the uploaded file being too big, I'll close this issue. Please open it again if you think there's something else going on.

**Closed by timvisee** 2019-08-04 21:38 UTC
