### ISSUE TITLE
Bug: thread 'main' panicked at 'failed to read header' on Ubuntu 16.04 Xenial 

### ISSUE THREAD

**Issue by VeilleurTrytoFix** [timvisee/ffsend#44] opened 2019-04-14 12:15 UTC
hello thanks for you jobs, i got on ubuntu1604 xenial :

./ffsend upload dummy.png

thread 'main' panicked at 'failed to read header from reader: Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by VeilleurTrytoFix** [comment] 2019-04-14 12:31
help command work

dummyuser@627712:~/$ ./ffsend 
ffsend 0.2.44
Usage: ffsend [FLAGS] <SUBCOMMAND> ...

Easily and securely share files from the command line.
A fully featured Firefox Send client.

Missing subcommand. Here are the most used:
    ffsend upload <FILE> ...
    ffsend download <URL> ...

To show all subcommands, features and other help:
    ffsend help [SUBCOMMAND]

**Comment by timvisee** [comment] 2019-04-15 21:36
Thank you for the report. It is not quite clear to me what is happening here right now.

Your first message noted `libssl` issues, but your latest edit doesn't explicitly mention that. I assume this is still caused by an unsupported `libssl` version.

Could you clarify what installation option you're currently using? If you're using a binary directly, what binary are you using from the [releases](https://github.com/timvisee/ffsend/releases), or are you using a package such as the [`snap`](https://github.com/timvisee/ffsend#linux-snap-package) package?

I assume you're using the regular binary (non-static) directly, which does indeed require `libssl` to be installed on your system. This shouldn't be necessary for the static variant, I therefore recommend you to give the [`*-linux-x64-static`](https://github.com/timvisee/ffsend/releases/latest) binary a try if you're not already using it.  
Your best bet might be to give the [`snap`](https://github.com/timvisee/ffsend#linux-snap-package) package a try if supported, it should have everything included.

Please make sure you've `apt-get install ca-certificates` installed on your system as well when using the binary.

**Comment by Cyber28** [comment] 2019-04-16 15:45
I am having exactly the same issue on Ubuntu 18.04. I installed with snap, and I have `ca-certificates` installed
I used `ffsend upload -p -C -o document.txt` and got the same error as above.

**Comment by Cyber28** [comment] 2019-04-17 16:20
Update: It seems to be working now for some reason
Running the same command as in my previous comment, I did get the output `user-open-error: Object does not implement the interface`

**Comment by timvisee** [comment] 2019-04-17 16:41
Very interesting. Thanks for the update, good to hear it works now.

It seems the actual panic is located here:
https://github.com/timvisee/ffsend-api/blob/472f50d570d843cc55b856274eb90a151bc70d3e/src/action/upload.rs#L379

Apparently it fails to read the first part of the payload send to the remote server, being the header with some upload information. I think this is due to a failed file read, for whatever reason, but I can't confirm that right now. It might be an encryption error as well. I'll do some debugging soon to see if I come across this panic (I haven't seen it yet). I might also attempt to improve error reporting for this issue, to get a better picture of what is wrong.

I'm wondering if this issue is reproducible, in certain directories (not in the home directory) or with specific file sizes for example.

It would be awesome if anyone that comes across this issue once again could answer the following questions in an attempt to debug what is going on here:
1. Does it happen every time with the same command, is the error consistent?
2. What command is used for the upload, causing this error?
3. What system are you using, Windows, Linux, or?
4. What installation option are you using, a binary, the `snap` package, or?
5. What is the current working directory? (Linux: `pwd`)
6. What is the exact file size in bytes? (Linux: `wc -c myfile.txt`)
7. Do you have permission to open the file?
8. Is your system up-to-date?

**Comment by Cyber28** [comment] 2019-04-18 06:01
I think I'm onto something. I tested with a variety of files of different sizes and formats, and so far I've found the issue occurs every time I upload an empty file (size: 0 bytes according to `wc -c myfile.txt`). Same error output as before.

**Comment by Cyber28** [comment] 2019-04-18 06:04
Actually, send.firefox.com doesn't even let you upload empty files. Perhaps that could be solved by ffsend checking the file size and rejecting if it's 0 or below a certain amount?

**Comment by timvisee** [comment] 2019-04-18 08:27
Thanks for reporting. That sounds sort of logical.

I'll patch this to throw an error for 0-sized files soon.

**Comment by timvisee** [comment] 2019-04-18 09:57
I can indeed confirm that uploading such a file causes an error. Thanks again for figuring this out.

I've created the following tracking issue over on GitLab to fix this issue:
https://gitlab.com/timvisee/ffsend/issues/86

I'll close this as soon as a fix is implemented.

**Comment by Cyber28** [comment] 2019-04-18 10:09
Glad I was able to help!

**Comment by timvisee** [comment] 2019-04-18 19:16
I've now added proper error handling for files being 0 bytes:  
![image](https://user-images.githubusercontent.com/856222/56385372-2e314580-621f-11e9-96f0-90de608174cc.png)

This improvement will be included in `v0.2.45`

**Closed by timvisee** 2019-04-18 19:16 UTC
Labels: bug
