### ISSUE TITLE
Can't upload file in /tmp/ ?

### ISSUE THREAD

**Issue by marcbelmont** [timvisee/ffsend#68] opened 2019-06-22 14:05 UTC
I can upload files located in my home directory. However, if they are in `/tmp` it fails. See below:

```shell
marc@marc-i7 ~ {master} 16:01:52$ ls -l /tmp/car*
-rw-r--r-- 1 marc marc 305144 Jun 22 11:01 /tmp/car.jpg
marc@marc-i7 ~ {master} 16:02:32$ ffsend u /tmp/car.jpg 
error: the path '/tmp/car.jpg' does not exist

For detailed errors try '--verbose'
For more information try '--help'
```

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

**Comment by timvisee** [comment] 2019-06-22 20:16
What kind of `ffsend` installation are you using, the `snap` package by any chance? Due to a `snap` limitation, these packages cannot access any files outside of your users home directory. See the following notice for [this](https://github.com/timvisee/ffsend/#linux-snap-package) installation option:

> _The `ffsend` `snap` package is isolated, and can only access files in your home directory. Choose a different installation option if you don't want this limitation._

Please pick another installation option if you prefer to have support for this. Moving the file into your home directory, and uploading it from there is possible but cumbersome.

I'll close this issue for now. Please open it again if this wasn't caused by the `snap` package option.

**Closed by timvisee** 2019-06-22 20:16 UTC

**Comment by marcbelmont** [comment] 2019-06-23 05:46
Yes I am using snap. Thanks for your quick response.
